spring:
  #redis基础配置
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis数据库索引（默认为0）
    database: 0
    # 前缀，添加之后会在key前拼接分组，【要有冒号】
    prefix: "ACGkaka:"
    # Redis服务器连接端口
    port: 6379
    # 链接超时时间 单位 ms（毫秒）
    timeout: 3000
    # 密码
    password: 123456
    # 连接池配置（jedis/lettuce）
    jedis:
      pool:
        # 连接池中的最大空闲连接 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
